import type {Metadata} from "next";

import "../styles/globals.css";
import {ApolloClientProvider} from "@/providers/ApolloClientProvider";
import { Inter } from 'next/font/google';

const inter = Inter({subsets: ["latin"]})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ApolloClientProvider>{children}</ApolloClientProvider>
            </body>
        </html>
    );
}
